# <font color='blue'><big>TENSORFLOW
https://www.tensorflow.org/api_docs/python/tf/compat/v1/Session?hl=es-419<br>
https://www.tensorflow.org/guide/migrate#1_replace_v1sessionrun_calls<br>

    
    
- Hay varios cambios de **TFv1 a TFv2**. Por favor chequear algunos en las paginas de los links.

## <font color='blue'>EAGER MODE en TensorFlow 2
https://medium.com/ai%C2%B3-theory-practice-business/tensorflow-1-0-vs-2-0-part-2-eager-execution-and-autograph-47473ed8b817<br>
    
- Con **EAGER MODE** no necesitamos una **``tf.Session``** para correr el código en TF. el entorno TensorFlow se comporta como cualquier código Python. Además podemos utilizar **if, while**, and **for**. 

- Con **EAGER MODE** se removieron de TF v1:
    - **``tf.Session``**
    - **``tf.Graph``**
    - **``tf.if``**, **``tf.while``**, **``tf.control_depnedencies``** (control flow directives)
    - **``placeholders``**
    - **``variable initialization``**
    - **``variable sharing``**

In [65]:
import numpy as np
import tensorflow as tf

In [3]:
tf.__version__

'2.6.0'

# ``tf.math.add(a, b)`` $\;$$\;$$\;$ ``tf.math.multiply(a, b)``

In [67]:
a = tf.constant(4)
b = tf.constant(6)
c = tf.math.add(a, b)
tf.print(c)

10


In [81]:
a = tf.constant(4)
b = tf.constant(6)
c = tf.math.multiply(a, b)
tf.print(c)

24


# ``tf.matmul(a, b)`` $\;$$\;$$\;$ ``tf.linalg.matmul(a, b)``

In [82]:
a = tf.constant([1, 2, 3, 4],shape=(1,4))
b = tf.constant([4,3,2,1],shape=(4,1))
c = tf.matmul(a, b)
tf.print(c)

[[20]]


In [85]:
# multiply matrices
a = tf.constant([1, 2, 3, 4],shape=(1,4))
b = tf.constant([4,3,2,1],shape=(4,1))
c = tf.math.multiply(a, b)
tf.print(c)

[[4 8 12 16]
 [3 6 9 12]
 [2 4 6 8]
 [1 2 3 4]]


In [87]:
a = tf.constant([1, 2, 3, 4],shape=(1,4))
b = tf.constant([4,3,2,1],shape=(4,1))
c = tf.linalg.matmul(a, b)
tf.print(c)

[[20]]


# ``tf.fill((fil,col),numero)``

In [20]:
my_fill = tf.fill((2,3),10)
my_fill

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 10, 10],
       [10, 10, 10]])>

# ``tf.zeros((fil,col))``
- Los parentesis dentro de los parentesis siempre tienen que estar para darle a la matriz las filas y columnas deseadas.


- Por ejemplo: 

    - **``tf.zeros((2,3)) = array([0., 0., 0.],[0., 0., 0.])``** $\;$$\;$$\;$ **>>> shape=(2, 3)**
    - **``tf.zeros(2,3) = array([0, 0])``** $\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$$\;$ **>>> shape=(2,)**
    

In [21]:
my_zeros= tf.zeros((2,3))
my_zeros

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [44]:
my_zeros2= tf.zeros(2,3)
my_zeros2

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 0])>

# ``tf.ones((fil,col))``

In [22]:
my_ones= tf.ones((2,3))
my_ones

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

## ``tf.random.normal(shape,mean=0.0,stddev=1.0,dtype=tf.float32,seed=None,name=None)``
- Devuelve valores aleatorios de una distribución normal.


- **dtype:** SOLO acepta **float**, no acepta **int**.  
    - **float16:** hasta 2 decimales. 
    - **float32:** hasta 4 decimales.
    - **float64:** hasta 8 decimales.


- **seed:** Para que funcione, antes de la linea de **``tf.random.normal``** hay que escribir una linea de comando **``tf.random.set_seed(n)``**

In [23]:
my_randn = tf.random.normal([2,3], mean=32, stddev=12, dtype=tf.float16,seed=5)
my_randn

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[17.88, 23.48, 11.03],
       [26.06, 34.9 , 30.48]], dtype=float16)>

### ``tf.random.set_seed(n)``
- Para poder utilizar el **seed** y elegir siempre los mismo valores.

In [32]:
tf.random.set_seed(2)
my_randnseed = tf.random.normal([2,3], mean=32, stddev=12, dtype=tf.float16,seed=5)
my_randnseed

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[27.31, 18.11, 42.5 ],
       [23.23, 32.9 , 51.44]], dtype=float16)>

## ``tf.random.uniform(shape,minval=N,maxval=N,dtype=tf.float/int,seed=N,name=N)``
- Devuelve valores aleatorios en una **Distribucion Uniforme** (Distribución Uniforme es cuando todos los valores entre un minimo y un maximo tienen las mismas posibilidades. Un ejemplo es lanzar un dado, ya que todos los 6 resultados posibles tienen 1/6 de probabilidad de ocurrencia cada uno)
- Pueden repetirse valores (de hecho, probando aparecieron valores identicos ente si)

In [92]:
my_randu = tf.random.uniform((2,3), minval=0, maxval=45, dtype=tf.int32)
my_randu

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[25, 44, 19],
       [42, 30, 10]])>

In [94]:
todos =[my_fill,my_zeros,my_ones,my_randn,my_randu]
todos

[<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10, 10, 10],
        [10, 10, 10]])>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float16, numpy=
 array([[17.88, 23.48, 11.03],
        [26.06, 34.9 , 30.48]], dtype=float16)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[25, 44, 19],
        [42, 30, 10]])>]

# ``tf.print()``

In [96]:
todos =[my_fill,my_zeros,my_ones,my_randn,my_randu]
tf.print(todos)

[[[10 10 10]
 [10 10 10]], [[0 0 0]
 [0 0 0]], [[1 1 1]
 [1 1 1]], [[17.875 23.484375 11.03125]
 [26.0625 34.90625 30.484375]], [[25 44 19]
 [42 30 10]]]


In [90]:
for uno in todos:
    tf.print(uno)
    tf.print('\n')

[[10 10 10]
 [10 10 10]]


[[0 0 0]
 [0 0 0]]


[[1 1 1]
 [1 1 1]]


[[17.875 23.484375 11.03125]
 [26.0625 34.90625 30.484375]]


[[44 9 22]
 [15 29 32]]


